### ISSUE TITLE
problem with the line ResourceDictionary

### ISSUE THREAD

**Issue by mksuper1** [Xavalon/XamlStyler#105]
Hi,
I have set the attribute tolerance to 4 so that it will break the lines if it has more than 4 attributes.
My problem is that sometimes the line ResourceDictionary  contains less than 4 attributes and this causes the line to merge into a single line.
e.g.
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" 
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

Is there any settings where I can always force the resource line to split into multiple lines with max attribute per line is set to 1.

thanks

**Comment by grochocki** [comment]
This scenario may be difficult with a single set of settings, since it could easily get complicated. Because you are looking to apply an entirely different set of formatting rules as an exception, it is not as easy to have something like [Newline Exception Elements](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#newline-exemption-elements), which does the opposite of what you are after.

If your ResourceDictionary is in a separate file, I would suggest using a per directory settings file and customize the configuration for the directory with the ResourceDictionary defined.

**Comment by grochocki** [comment]
Closing discussion due to lack of activity. If further discussion is warranted, feel free to reopen issue.
