### ISSUE TITLE
How to keep xmlns in separate lines if MaxAttribute is set to 2

### ISSUE THREAD

**Issue by nologinatgit** [Xavalon/XamlStyler#124]
I set the **MaxAttribute** to 2 but I want to see each **_xmlns_** in _separate rows_ as defined in the main tag.

Unfortunately, XAMLStyler reorders them like this:

```xaml
<UserControl
xmlns:local="clr-namespace:MyProject" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:d="http://schemas.microsoft.com/expression/blend/2008">
```

I can't add it to any exemption list to leave it alone.

How can I do it without setting the MaxAttribute to 1?

**Comment by grochocki** [comment]
Thanks for the feature request! However, it does introduce some complications. If we somehow special-case styling in the "main tag", it is a slippery slope to special-casing other elements. Even with just the "main tag" it becomes a configuration nightmare, because while you might desire MaxAttribute to be 1, someone else might want all the attributes on one line (or any combination of other options). Because of this, we are going to err on the side of consistency of formatting all XAML based on one configuration and not pursuit this feature for now.

**Comment by dorufoaltin** [comment]
Can't you add a  bool property, lets say "Keep namespaces (xmlns:) in one line" to enable keeping each xmlns in separate rows? 

In my view, this would avoid the configuration nightmare mentioned above. 

If not possible, can you tell us how we can keep MaxAttribute > 1, and also keep xmlns in separate rows?

**Comment by heartacker** [comment]
I beg，And can anybody make a PR
