### ISSUE TITLE
TextBlock formatting is changing spacing

### ISSUE THREAD

**Issue by jamre** [Xavalon/XamlStyler#130]
This could be related to #87 

I am using the v3.1 extension in Visual Studio 2017 (15.4.4)

If I have this xaml:
```xml
<TextBlock>Some <Underline>U</Underline>nderlined and B<Bold>old</Bold>ed.</TextBlock>
```
I get output like this (I can't underline here, but the U is underlined):
> Some Underlined and B**old**ed.

After formatting, the xaml is like this:
```xml
<TextBlock>
    Some<Underline>U</Underline>
    nderlined and B<Bold>old</Bold>
    ed.</TextBlock>
```

Which produces this (the U is underlined):
> SomeU nderlined and B**old** ed.

**Comment by jamre** [comment]
Perhaps it would be a more accurate bug description to say that [inline flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline?view=netframework-4.7.1) should not cause a line break or affect spacing. Or maybe they should just be completely ignored?

**Comment by grochocki** [comment]
Seems related to #81/#120. I am betting the free text outside of any tags is the cause here (and something that was missed in previously mentioned PR). I am not able to test right now, but if you wrap all the content of the TextBlock in a `<span>`, does that fix it? If so, that might be a viable workaround until we can fix the underlying issue. If not, I will have to dig into it a bit more to see what is going on.

**Comment by jamre** [comment]
I just tried with a span.
```xml
<TextBlock><Span>Some <Underline>U</Underline>nderlined and B<Bold>old</Bold>ed.</Span></TextBlock>
```
produced:
```xml
<TextBlock><Span>
    Some<Underline>U</Underline>
    nderlined and B<Bold>old</Bold>
    ed.</Span></TextBlock>
```

Which still had the same bad spacing.

**Comment by grochocki** [comment]
Thanks for trying this out! I will have to dig into this a bit more, but theoretically, any use of those inline flow content elements should preserve spacing.

**Comment by kempust** [comment]
You can work around this by adding xml:space="preserve" to the <TextBlock> tag

**Comment by grochocki** [comment]
While investigating the fix for #203, we discovered that the "workaround" to use the ```xml:space="preserve"``` attribute is actually the intended solution to address cases where you want to mix [inline-level flow content elements](https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inline) with other text. I've updated the [Wiki](https://github.com/Xavalon/XamlStyler/wiki/Getting-Started#whitespace) to reflect this.

>Perhaps it would be a more accurate bug description to say that inline flow content elements should not cause a line break or affect spacing. Or maybe they should just be completely ignored?

When not mixed with other text, we _do_ want formatting to occur. Since we cannot reliably handle mixed cases, preserving spacing is the best override here.

**Comment by Symbai** [comment]
I'm not sure if this should be "by design" at all. The workaround with using  `xml:space="preserve"` still works yes, but imagine you have a LONG text with more than 300 words. For a better readability in XAML you will add your own line breaks. But using `xml:space="preserve"` will also append LOTS of unwanted white spaces for each of these line breaks. The only way to fix this is to write the whole text in ONE single line. This is awful behavior.

It should somehow detect if its inline text and then don't format it. At least there should be an option.

**Comment by Slion** [comment]
I was having a hard time keeping trailing a space in `TextBlock` as I apparently needed to that for L10N purposes. I ended up having to use `<TextBlock><Run>&#160;</Run></TextBlock>` as in:

```
                        <!-- Peeking delay slider -->
                        <c:SettingsCard x:Uid="SettingsCardPointToPeekDelay" IsEnabled="{x:Bind Settings.PeekWhenOverItem, Mode=OneWay}">
                            <c:SettingsCard.Description>
                                <c:WrapPanel Orientation="Horizontal">
                                    <TextBlock x:Uid="TextBlockPointToPeekDelayBegin" />
                                    <TextBlock><Run>&#160;</Run></TextBlock>
                                    <TextBlock Text="{x:Bind iSliderDelay.Value, Mode=OneWay}" />
                                    <TextBlock><Run>&#160;</Run></TextBlock>
                                    <TextBlock  x:Uid="TextBlockPointToPeekDelayEnd" />
                                </c:WrapPanel>
                            </c:SettingsCard.Description>
                            <Slider x:Name="iSliderDelay" Value="{x:Bind Settings.PeekWhenOverItemDelay, Mode=TwoWay}" Minimum="0" Maximum="3000" StepFrequency="100" SmallChange="50" />
                        </c:SettingsCard>
```
