### ISSUE TITLE
Grid Binding properties not stacked

### ISSUE THREAD

**Issue by qck1** [Xavalon/XamlStyler#143]
When you run XAML Styler on a control like a ContentControl the attributes are stacked like such:
                        <ContentControl Grid.Row="0"
                                                    Grid.Column="3"
                                                    Style="{StaticResource GreenCheckControl}"
                                                    Visibility="{Binding ChannelStatus,
                                                                                    Converter={common:IsEqualConverter},
                                                                                    ConverterParameter=Pass?Visible:Collapsed}" />

but at the same tile the Gird Binding attributes are not:

                    <Grid Visibility="{Binding ElementName=DisplayControlToggleButton, Path=IsChecked, Converter={common:IsTrueConverter}, ConverterParameter=Collapsed:Visible}">

The same is true for a Style Setter:
                        <Setter Property="Foreground" Value="{Binding ChannelStatus, Converter={common:IsEqualConverter}, ConverterParameter={wpfApp1:Concat String='Ignore?Orange:Pass?{StatusGreenBrush}:{StatusRedBrush}'}}" />

**Comment by grochocki** [comment]
@qck1, it looks like the sample code for ContentControl is missing. Can you update your comment to include this?

**Comment by grochocki** [comment]
Check the [Keep markup extensions of these types on one line](https://github.com/Xavalon/XamlStyler/wiki/Markup-Extension-Handling#keep-markup-extensions-of-these-types-on-one-line) setting. "Binding" and "x:Bind" are always kept on a single line, so I believe this is by design. Please feel free to reopen and provide more details if this does not address your issue.
