### ISSUE TITLE
How to align attribute only ?

### ISSUE THREAD

**Issue by GreatFireWall** [Xavalon/XamlStyler#157]
### Example:
from
```
<Tag Name="abc" X="asdas" Y="asddsfd"
              A="asdad"
      B="asdsa"
                        C="asds" />
```
to
```
<Tag Name="abc" X="asdas" Y="asddsfd"
     A="asdad"
     B="asdsa"
     C="asds" />
```
keep X and Y not break line.

**Comment by grochocki** [comment]
What configuration yields the first code sample?

**Comment by GreatFireWall** [comment]
some times I will typing these, the actual situation is simpler than this.

**Comment by grochocki** [comment]
XAML Styler does not understand developer intent, so it applies a ruleset across the entire file. There is not a great way to differentiate between when you might want the entire element to be formatted and when you might want the first line to be ignored. In this case, you may be able to set [First Line Attributes](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Reordering#first-line-attributes), so that certain attributes always stay on the first line. Alternatively, if you would prefer to format based on the total length that attributes takes up, perhaps take a look at [Max Attribute Characters Per Line](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#max-attribute-characters-per-line) and [Max Attributes Per Line](https://github.com/Xavalon/XamlStyler/wiki/Attribute-Formatting#max-attributes-per-line).
