### ISSUE TITLE
VSMac: Attribute Indentation Style 'Mixed' not applied

### ISSUE THREAD

**Issue by InquisitorJax** [Xavalon/XamlStyler#211]
When I set the attribute indentation style to "Mixed", I'm expecting tabs, mixed with spaces to indent the attributes, but tabs are not applied. The whole file remains spaces.

All the latest bits installed (VS Mac + Extension 1.1.5)

**Comment by InquisitorJax** [comment]
Tabs are being replaced by spaces.
Basically - we need the behavior to be consistent between VS for Mac and VS for Win.
Currently in the windows extension, 'Mixed' means everything is tabbed except for the attribute indentation.

**Comment by grochocki** [comment]
> Basically - we need the behavior to be consistent between VS for Mac and VS for Win.

100% agree.

> Currently in the windows extension, 'Mixed' means everything is tabbed except for the attribute indentation.

Yep, basically, we respect existing tabs while using spaces for any changes.

@Saratsin -- any thoughts on how to align VS for Mac with VS here?

**Comment by InquisitorJax** [comment]
@Saratsin any updates on this?
This is causing us quite a bit of issues merging changes in xaml files :(

**Comment by InquisitorJax** [comment]
@Saratsin @grochocki do we have an eta on this guy?

**Comment by Saratsin** [comment]
@InquisitorJax will check it at weekends and write back here updates

**Comment by Saratsin** [comment]
Okay so. There's no easy solution currently.
We don't have currently ability to read Visual Studio for Mac extension.
That's why we also don't handle Visual Studio indent size on Mac.
I'll try to fix this misconception in next releases, but for now I have one proposal: make `Indent with tabs` option for Mac, to have ability to configure it, until I or someone else will provide the correct solution
![image](https://user-images.githubusercontent.com/16039381/72686512-5f1c0f00-3afe-11ea-9ad9-a77bb224475b.png)

**Comment by InquisitorJax** [comment]
@Saratsin That sounds like a good proposal. At the end of the day, we just need the ability for the xaml to be formatted the same way so we don't end up submitting PRs that have file changes polluted by different formatting.

**Comment by Saratsin** [comment]
@InquisitorJax v2.0.1 is now available
