### ISSUE TITLE
"&" character is not recognized and due which formatting not working. 

### ISSUE THREAD

**Issue by shubhambhosale** [Xavalon/XamlStyler#284]
**Describe the bug**
When we have added the "&" character on the page as text value then the XamlStyler is not recognizing it and giving the error.  
Please find the attached screenshot below. In screenshot you can find when we set the label text with "&" and then call XamlStyler it is giving error.

**Screenshots**
![image](https://user-images.githubusercontent.com/26299688/82211892-3cc0c380-992f-11ea-8d98-eb52c8f976ca.png)

**Version Info (please complete the following information):**
 - OS: Windows 10 (1903)
 - Visual Studio: VS2019 (16.4.1)
 - XAML Styler: Extension (3.2003.9)

**Comment by grochocki** [comment]
Thanks! I was able to confirm issue -- investigating.

**Comment by grochocki** [comment]
This seems to be an instance of leveraging a XML character entity. In this case, you should use ```&amp;``` to encode the ampersand in ```Label.Text```.

This is a possible candidate for surfacing in some sort of error/warning UI in the future as part of #271, but this is otherwise by design due to XAML language spec. Here is some more information on [XML Character Entities and XAML](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/xaml-services/xml-character-entities).
