### ISSUE TITLE
Add option to ignore design-time reference prefix when reordering

### ISSUE THREAD

**Issue by mturczyn** [Xavalon/XamlStyler#306]
I recently started using more often design time properties, which requires to include blend namespace:
```
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
```

It leads to having "double" properties, such as:
```
<Label
    d:Content="Hello design world"
    Content="Hello world from runtime" />
```

Using styler, it separates the two, if there are other properties, which, by default would go between the two.

But I would like to have this behaviour disabled,  i.e. properties which differ only by design time namespace, I want them together as much as possible. 

It makes easier to read the XAML code, as I see instantly what property is and if it has design time value set.

I forked the repo and I can try to develop this feature. I think it won't be huge thing to carry out.

**Comment by grochocki** [comment]
Great idea, @mturczyn! Have you considered tying this to the designated design-time reference namespace prefix? I am imagining something like this:

**Display Name:** "Ignore Design-Time Reference Prefix"
**Property:** IgnoreDesignTimeReferencePrefix
**Category:** Attribute Reordering
**Description:** Defines whether the design-time reference namespace prefix ("d:") is ignored when ordering attributes.
**Default:** false

**Comment by mturczyn** [comment]
@grochocki I don't understand "designated design-time reference namespace prefix" part.

My idea which I implemented, is to:
1. Take namespaces ignnored in ordering from settings (eg. "http://schemas.microsoft.com/expression/blend/2008")
2, When styling XAML, first scan file to find defined namespaces in file. This way I get the prefixes denoting those ignored namespaces.
3. When styling, ignore those attributes, which differ only by prefix denoting design time namespace.

I created pull requests, so you can see it in action :)

**Comment by grochocki** [comment]
@mturczyn I consulted with a few folks and I like what you are doing to leverage the namespace instead of the prefix (since someone could use something other than the standard/default of 'd'), but exposing a free form option feels heavy when there is a limited set of design namespaces. So, we'd like to propose a hybrid between my original suggestion and your implementation where we keep the exposed option a bool, but derive the prefix from the hardcoded namespace. If there are additional design namespaces added in the future, we can update that list.

> When styling XAML, first scan file to find defined namespaces in file. This way I get the prefixes denoting those ignored namespaces.

Are two passes strictly necessary? I am wondering if we can optimize this by looking in the root node for the namespaces upfront.

**Comment by mturczyn** [comment]
@grochocki Hi!
I considered your suggestion and implemeneted accordingly :) 
Also found one bug with ordering rules and corrected that :) 
You can find all this in my pull request.
