### ISSUE TITLE
Create Releases for VS for Mac extension

### ISSUE THREAD

**Issue by Saratsin** [Xavalon/XamlStyler#325]
Monodevelop addins repository is no longer working.

Instead Microsoft provides new approach with GitHub Releases and special tags to provide new version of extensions for VS for Mac.

So I think it will be a good idea to implement this approach in this repository or as alternative, create separate repository with its only function to provide new versions of Visual Studio for Mac extesion

**Comment by grochocki** [comment]
Closing this as won't fix since [Visual Studio for Mac is scheduled for retirement by August 31, 2024](https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022).

We've published the binary on the [downloads page in the wiki](https://github.com/Xavalon/XamlStyler/wiki) for those looking for it.
