### ISSUE TITLE
Please make available for VS 2022

### ISSUE THREAD

**Issue by BillyMartin1964** [Xavalon/XamlStyler#344]
Love this extension, but also love 64 bit Visual Studio. Please make this available for Visual Studio 2022 as soon as possible. Thanks

**Comment by mrkrk** [comment]
Started using VS 2022 for all my Xamarin apps. But when I do CTRL + S and XAML does not format makes we wanna use 2019.
XAML development experience is inferior without this tool.
Can you share the timeline of when this tool might be available?

**Comment by PrimoDev23** [comment]
So I made xaml styler working for VS 2022 (can't put a release there right now - give me about an hour)
But here is the repository

https://github.com/PrimoDev23/XamlStyler

You can simply build it yourself by building the solution or wait for me to add a release
Versioning is quite messy because I tested some things but it's working until we get an official release

**Comment by BillyMartin1964** [comment]
I don't understand how to install it into visual studio 2022

**Comment by PrimoDev23** [comment]
> I don't understand how to install it into visual studio 2022

Download the vsix file under releases and execute it. It will open an installer

**Comment by grochocki** [comment]
Using #353 to track status for VS2022 Support

**Comment by Nk54** [comment]
Same as @mrkrk : without XamlStyler, my team won't adopt VS 2022.

Without homogenous XAML file format, it becomes a nightmare and my team spend too much time on pull request to comment about XAML format style mistake instead of focusing on the business.

XamlStyler should be shipped within Visual Studio 2022.

**Comment by Nk54** [comment]
Here it is !
https://marketplace.visualstudio.com/items?itemName=TeamXavalon.XAMLStyler2022

**Comment by AleksTozik** [comment]
Amazing  for windows, could you adopt it for vs for mac?

**Comment by grochocki** [comment]
The documentation on VS4Mac is pretty light and a bit confusing, but we'd love to update support. More discussion on this in #384.

**Comment by sergey19941201** [comment]
Please make it for the VS 2022 Mac
