### ISSUE TITLE
Support for Rider 2022.2

### ISSUE THREAD

**Issue by cetso** [Xavalon/XamlStyler#402]
Please add support for Rider 2022.2

**Comment by crypto-rsa** [comment]
The PR has been merged a week ago but still no new release. Is it waiting for something else?

**Comment by grochocki** [comment]
Version 3.2208.0.0 has been submitted to JetBrains for review. Update should be available within ~2 days!

**Comment by crypto-rsa** [comment]
The updated package is now available through the JetBrains Marketplace. Thanks @grochocki. However, for such a simple change (updating the version number in a few places), I'd expect a much quicker turnaround. The community can certainly help with the pull request itself but preparing the release is a work for the maintainers. Can we kindly ask for more attention next time? 🙏

**Comment by NicoVermeir** [comment]
hi @crypto-rsa while I understand your statement, please keep in mind that this project is run by a few volunteers in their spare time, we gain nothing from this project, we do this purely out of love for the community and our jobs. That also means that from time to time things will take a bit longer because of work, family or other personal reasons.

Rest assured that we do our very best to keep this project in an active state 😊

thank you for your support and your understanding!
