### ISSUE TITLE
Put events together

### ISSUE THREAD

**Issue by hupo376787** [Xavalon/XamlStyler#403]
**Is your feature request related to a problem? Please describe.**
Now the events and property are mixed together, so it's hard to find events.
![image](https://user-images.githubusercontent.com/14960168/182816168-14aa8336-106b-4d17-a8d2-ad499862c5ca.png)

**Describe the solution you'd like**
Put events together, and move to last.
![image](https://user-images.githubusercontent.com/14960168/182816309-4140bfff-2f05-459f-a81f-a17c4f03742b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by NicoVermeir** [comment]
Thanks for the idea @hupo376787 
The way XAML Styler works is that it looks at XAML like a normal XML file. It has no knowledge of what attribute or property is an event or another type. So in order to make this work we would either need to add a list of all events for every element to figure this stuff out.

What we do have in XAML Styler that might help you is either putting the most common events in an attribute ordering group, or just disable attribute reordering in the settings.

![image](https://user-images.githubusercontent.com/3177418/185045230-fdbd0363-dfce-44af-b6bf-a0924821fd87.png)

@grochocki feel free to chime in here if you have other ideas :)

**Comment by hupo376787** [comment]
Thanks for the reply. @NicoVermeir
