### ISSUE TITLE
No such interface supported

### ISSUE THREAD

**Issue by kfrancis** [Xavalon/XamlStyler#477]
I'm getting errors lately from the extension when trying to just save other types of XML files.

**To Reproduce**
1. Edit project file (csproj)
2. Save

**Expected behavior**
Nothing should happen, since I'm not actually working on a xaml file.

**Actual**
This exception occurs.
![image](https://github.com/Xavalon/XamlStyler/assets/67574/e8b0edf0-c9a0-4d08-972d-767dfbdf18cf)

**Version Info (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22631.3374]
 - Visual Studio: 2022 Version 17.9.5
 - XAML Styler: Extension 3.2311.2

**Comment by Cfun1** [comment]
I see there is already a `SupportedExtensions` used in [console part](https://github.com/search?q=repo%3AXavalon%2FXamlStyler%20SupportedExtensions%20&type=code), but seems the other parts are not doing the check on file type.

At the same time the below line is supposed to filter xaml only files right!?
https://github.com/Xavalon/XamlStyler/blob/3663f178854bf7a3b7109f225872b39ce63c6f19/src/XamlStyler.Extension.Windows.Shared/StylerPackage.cs#L33

**Comment by grochocki** [comment]
I am investigating a blocking issue with the release build of the extension for VS2022 that is preventing it from loading properly. Unfortunately, I am not unable to deploy the extension under debug, blocking progress (#479). The reported issue is fixed by #453, which will be included in that upcoming release, so closing this issue.
