### ISSUE TITLE
Issue when trying to use external config file

### ISSUE THREAD

**Issue by keekis** [Xavalon/XamlStyler#491]
Work when I specify absolute path like C:\repo\dev\xamlstyler.json
Don't work if I I set "Search to drives root" like shown in picture below
![image](https://github.com/Xavalon/XamlStyler/assets/14963858/f502f3d9-4c56-4906-b6cd-ab72b7bdaa82)

xamlstyler.json file contains following:
[xamlstyler.json](https://github.com/user-attachments/files/15886080/xamlstyler.json)

**Comment by grochocki** [comment]
External configuration file is intended to specify an absolute path for configuration files outside of project hierarchy. Otherwise, you can leave this blank, and it will be picked up automatically if you follow standard file naming convention ("Settings.XamlStyler"). Some more information on External Configurations [here](https://github.com/Xavalon/XamlStyler/wiki/External-Configurations).

**Comment by keekis** [comment]
Great. Thanks. It worked when I renamed the file to Settings.XamlStyler.
If not already documented (I might have missed it) - I suggest to include this in the documentation :).

**Comment by grochocki** [comment]
Great! I emphasized file name in the doc as it might have been easy to miss.
