### ISSUE TITLE
Default value for Reorder canvas and grid panel children in Settings grid not shown as such

### ISSUE THREAD

**Issue by jeroenwalter** [Xavalon/XamlStyler#88]
Xaml styler 2.4
I would expect the default values in the settings grid to be shown in a bold font.
However, for at least the the two items 'reorder canvas panel children' and 'reorder grid panel children' this is not the case.
Their descriptions show that the default value is false, as this was changed in 2.3. But the grid shows the True value in bold. See screenshot.
There may be other settings that also exhibit this fault, but I didn't look for them.

![xamlstyler](https://cloud.githubusercontent.com/assets/1812838/22099081/27323e18-de2a-11e6-9bf5-2267ba3ceb7a.png)

**Comment by grochocki** [comment]
When upgrading from an older version, if the defaults change, the old default value is retained. I would have to look into it a bit more, but I believe this is just due to how extension settings are stored in VS. The nice thing about this is that a change in a default value will not unexpectedly change your styling options, potentially causing ill effects. There is also no real way to tell if the old default is set because it was the default or because the user actively wants it to be that value, so migrating the default would not be trivial. Resetting all settings to default is also out of the question, since that might be even more disruptive. If the new defaults suit your needs better, you can always "reset to default" at the bottom of options as a quick way to snap to the new values.

**Comment by jeroenwalter** [comment]
I agree that settings shouldn't be changed automatically, 
However that's not what this is about. 
It is about how the property grid shows default values. It does this incorrectly. 
The default value for the reorder items was changed from True to False, so I expect that False will be shown in bold and True not, regardless of any previous default values.

**Comment by grochocki** [comment]
Changed values are bolded, not the default values. Since the default was updated to False, but the stored value remained the old default value of True, in the Settings UI, since the stored value is not the same as the current default, it is bolded.

**Comment by jeroenwalter** [comment]
Of course....
I feel stupid now.... :)
